version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    commit-message:
      prefix: "[npm]"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
    commit-message:
      prefix: "[docker]"
    groups:
      docker-dependencies:
        patterns:
          - "*"
